//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temporizador.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Temporizador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.ComponentModel;
        ///
        ///namespace CreacionBotones
        ///{
        ///    public class BotonPersonalizado1 : Button
        ///    {
        ///        //Fields
        ///        private int borderSize = 2;
        ///        private int borderRadius = 20;
        ///        private Color borderColor = Color.Gold;
        ///
        ///        //Properties
        ///        [Category(&quot;RJ  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BotonPersonalizado1 {
            get {
                return ResourceManager.GetString("BotonPersonalizado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.ComponentModel;
        ///
        ///namespace CreacionBotones
        ///{
        ///    public class BotonPersonalizado2 : Button
        ///    {
        ///        //Fields
        ///        private int borderSize = 1;
        ///        private int borderRadius = 0;
        ///        private Color borderColor = Color.Black;
        ///
        ///        //Properties
        ///        [Category(&quot;RJ  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BotonPersonalizado2 {
            get {
                return ResourceManager.GetString("BotonPersonalizado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.ComponentModel;
        ///using System.Diagnostics;
        ///
        ///namespace Eventos_02
        ///{
        ///    public class BotonPersonalizado3 : Button
        ///    {
        ///        //Fields
        ///        private int borderSize = 2;
        ///        private int borderRadius = 0;
        ///        private Color borderColor = Color.Blue;
        ///
        ///        //Properties
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BotonPersonalizado3 {
            get {
                return ResourceManager.GetString("BotonPersonalizado3", resourceCulture);
            }
        }
    }
}
